use std::path::PathBuf;

use crate::session::SessionId;

/// In-memory snapshot of shared state across all talos instances.
///
/// Used for computing deltas between local and database state.
#[derive(Debug, Clone)]
pub struct SharedState {
    /// Session counter for unique naming across instances.
    pub session_counter: usize,

    /// Active sessions across all instances.
    pub sessions: Vec<SharedSession>,
}

impl SharedState {
    /// Create a new empty shared state.
    pub fn new() -> Self {
        Self {
            session_counter: 0,
            sessions: Vec::new(),
        }
    }
}

impl Default for SharedState {
    fn default() -> Self {
        Self::new()
    }
}

/// A session known to the shared state.
///
/// Tracks essential metadata needed for all instances to see and adopt sessions.
#[derive(Debug, Clone, PartialEq)]
pub struct SharedSession {
    /// Unique session identifier (generated by spawning instance).
    pub id: SessionId,

    /// Human-readable session name (e.g., "1", "Session 1").
    pub name: String,

    /// Coding agent driving this session (e.g., "claude", "codex").
    pub agent: String,

    /// Backend identifier for finding the session in tmux.
    /// Format: "talos:@0" for local tmux sessions.
    pub backend_id: String,

    /// Backend type (e.g., "tmux").
    pub backend_type: String,

    /// The underlying agent session ID (if started).
    pub agent_session_id: Option<String>,

    pub cwd: Option<PathBuf>,

    /// Extra directories (beyond `cwd`) this session spans. When a session has
    /// more than one member dir, the agent is launched in a per-session symlink
    /// workspace gathering them all (see `crate::workspace`), so every agent —
    /// not just those with an `--add-dir`-style flag — can reach them.
    pub additional_dirs: Vec<PathBuf>,

    pub worktrees: Vec<SharedWorktree>,

    /// Backend ID of the companion shell pane (if spawned).
    pub shell_backend_id: Option<String>,

    /// Parent session (lead/worker relationship for orchestration).
    /// `None` for top-level sessions. Purely informational: deleting the
    /// parent does not cascade to children.
    pub parent_session_id: Option<SessionId>,

    /// Manual position in the session list. `None` = never moved: renders
    /// after all ordered sessions, in creation order.
    pub display_order: Option<i64>,

    /// Tombstone flag: true if this session was soft-deleted.
    /// Soft-deleted sessions are excluded from active listings.
    pub tombstone: bool,

    /// Timestamp when this session was tombstoned (millis since epoch).
    pub tombstone_at: Option<u64>,
}

/// Worktree information embedded in shared session.
#[derive(Debug, Clone, PartialEq)]
pub struct SharedWorktree {
    /// Path to the git repository root.
    pub repo_path: PathBuf,

    pub worktree_path: PathBuf,

    pub branch: String,

    /// Whether talos checked this worktree out itself.
    ///
    /// False when the session merely *opened* a worktree the user already had.
    /// Force-delete removes only what talos created: `git worktree remove
    /// --force` deletes the directory and any uncommitted work in it, which is
    /// talos's to discard for a worktree it made and never for one it
    /// borrowed. Persisted (schema v42) because the decision outlives the
    /// process that made it.
    pub created_by_talos: bool,
}

impl From<crate::session::WorktreeInfo> for SharedWorktree {
    fn from(wt: crate::session::WorktreeInfo) -> Self {
        Self {
            repo_path: wt.repo_path,
            worktree_path: wt.worktree_path,
            branch: wt.branch,
            created_by_talos: wt.created_by_talos,
        }
    }
}

impl From<SharedWorktree> for crate::session::WorktreeInfo {
    fn from(wt: SharedWorktree) -> Self {
        Self {
            repo_path: wt.repo_path,
            worktree_path: wt.worktree_path,
            branch: wt.branch,
            created_by_talos: wt.created_by_talos,
        }
    }
}

/// Get current time in milliseconds since Unix epoch.
pub fn current_time_millis() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_shared_state_is_empty_and_valid() {
        let state = SharedState::new();
        assert_eq!(state.session_counter, 0);
        assert!(state.sessions.is_empty());
    }

    #[test]
    fn default_state_equals_new() {
        let new_state = SharedState::new();
        let default_state = SharedState::default();
        assert_eq!(new_state.session_counter, default_state.session_counter);
    }

    #[test]
    fn worktree_info_to_shared_worktree() {
        let wt = crate::session::WorktreeInfo {
            repo_path: PathBuf::from("/repo"),
            worktree_path: PathBuf::from("/repo/.git/wt/feat"),
            branch: "feat".to_string(),
            created_by_talos: true,
        };

        let shared: SharedWorktree = wt.into();
        assert_eq!(shared.repo_path, PathBuf::from("/repo"));
        assert_eq!(shared.worktree_path, PathBuf::from("/repo/.git/wt/feat"));
        assert_eq!(shared.branch, "feat");
    }

    #[test]
    fn shared_worktree_to_worktree_info() {
        let shared = SharedWorktree {
            repo_path: PathBuf::from("/repo"),
            worktree_path: PathBuf::from("/repo/.git/wt/feat"),
            branch: "feat".to_string(),
            created_by_talos: true,
        };

        let wt: crate::session::WorktreeInfo = shared.into();
        assert_eq!(wt.repo_path, PathBuf::from("/repo"));
        assert_eq!(wt.worktree_path, PathBuf::from("/repo/.git/wt/feat"));
        assert_eq!(wt.branch, "feat");
    }
}
